name: Test coverage

on:
  push:
    branches: [main, develop]

jobs:
  Coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      - name: Set up with Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Download dependencies
        run: npm ci
      - name: Generate coverage report
        run: ./node_modules/.bin/jest --coverage
      - name: Upload coverage to Quality
        uses: qltysh/qlty-action/coverage@v1
        env:
          QLTY_COVERAGE_TOKEN: ${{ secrets.QLTY_COVERAGE_TOKEN }}
        with:
          files: coverage/lcov.info
