name: Test coverage

on:
  push:
    branches: [main, develop]

jobs:
  Coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      - name: Set up with Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Download dependencies
        run: npm ci
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: ./node_modules/.bin/jest --coverage
