name: Deploy to GitHub Pages

on:
  workflow_dispatch:  # Manual trigger from Actions tab

permissions:
  contents: read      # Read repo contents
  pages: write        # Publish to Pages
  id-token: write     # Authenticate with GitHub Pages

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd browser
          npm ci

      - name: Build Vite site
        run: |
          cd browser
          npm run build

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: browser/buildweb

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deploy
