name: jsontests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  SpecTests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      - name: Set up with Node.js  LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Download dependencies
        run: npm ci
      - name: Test with Node.js LTS
        run: npm run testSpecs
