name: Tests

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  Build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 'node']

    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      - name: Set up with Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Print Node.js version and CI environment
        run: |
          echo "Node.js version: $(node -v)"
          echo "Environment: CI=${{ env.CI }}"
      - name: Download dependencies
        run: npm ci
      - name: Test with Node.js ${{ matrix.node-version }}
        run: npm test

  JSON-spec-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 'node']

    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      - name: Set up with Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Print Node.js version and CI environment
        run: |
          echo "Node.js version: $(node -v)"
          echo "Environment: CI=${{ env.CI }}"
      - name: Download dependencies
        run: npm ci
      - name: Run JSON spec tests with Node.js ${{ matrix.node-version }}
        run: npm run testSpecs
